package tr.borsatakip.v3

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity

/**
 * Compatibility activity kept for older references.
 * The V4 launcher is MainActivityV4, generated by the release workflow.
 */
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }
}
