from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
RES=ROOT/'app/src/main/res'; DRAW=RES/'drawable'; VALUES=RES/'values'; SRC=ROOT/'app/src/main/java/tr/borsatakip/v3'
(VALUES/'colors.xml').write_text('''<resources><color name="bg">#01192D</color><color name="nav_bg">#02121F</color><color name="surface">#061B2D</color><color name="border">#174662</color><color name="primary">#18A5FF</color><color name="green">#10D977</color><color name="yellow">#FFC53D</color><color name="orange">#FF8A1F</color><color name="red">#FF4055</color><color name="purple">#7452FF</color><color name="text_primary">#F4F7FB</color><color name="text_secondary">#A7B5C8</color><color name="text_muted">#8294AA</color><color name="bist_blue">#18A5FF</color><color name="viop_purple">#7452FF</color><color name="opportunity_orange">#FF8A1F</color><color name="positive_bg">#063C2B</color><color name="negative_bg">#3D1620</color><color name="neutral_bg">#092033</color></resources>\n''',encoding='utf-8')
(VALUES/'styles.xml').write_text('''<resources><style name="DashboardCard"><item name="android:layout_width">0dp</item><item name="android:layout_height">82dp</item><item name="android:layout_columnWeight">1</item><item name="android:layout_margin">4dp</item><item name="android:background">@drawable/bg_surface</item><item name="android:gravity">center_vertical</item><item name="android:padding">14dp</item><item name="android:textColor">@color/text_primary</item><item name="android:textSize">13sp</item></style><style name="NavItem"><item name="android:layout_width">0dp</item><item name="android:layout_height">match_parent</item><item name="android:layout_weight">1</item><item name="android:gravity">center</item><item name="android:textColor">@color/text_muted</item><item name="android:textSize">10sp</item><item name="android:fontFamily">sans</item><item name="android:paddingTop">4dp</item><item name="android:paddingBottom">4dp</item></style><style name="DashboardButton" parent="Widget.AppCompat.Button"><item name="android:layout_width">match_parent</item><item name="android:layout_height">54dp</item><item name="android:textAllCaps">false</item><item name="android:textSize">15sp</item><item name="android:textStyle">bold</item><item name="android:textColor">@color/text_primary</item><item name="android:background">@drawable/bg_surface</item><item name="android:minHeight">54dp</item></style></resources>\n''',encoding='utf-8')
(DRAW/'bg_surface.xml').write_text('''<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle"><solid android:color="#092033"/><stroke android:width="1dp" android:color="#174662"/><corners android:radius="18dp"/></shape>\n''',encoding='utf-8')
def grad(n,a,b,c): (DRAW/n).write_text(f'''<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle"><gradient android:startColor="{a}" android:endColor="{b}" android:angle="0"/><stroke android:width="1dp" android:color="{c}"/><corners android:radius="20dp"/></shape>\n''',encoding='utf-8')
grad('bg_bist.xml','#0B9BFF','#0754C7','#087ED1');grad('bg_opportunity.xml','#08B66B','#017447','#08C878');grad('bg_viop.xml','#594DFF','#2929A7','#7452FF')
layout=RES/'layout/activity_main.xml'; s=layout.read_text(encoding='utf-8'); s=s.replace('android:paddingStart="12dp" android:paddingEnd="12dp" android:paddingTop="8dp" android:paddingBottom="8dp"','android:paddingStart="16dp" android:paddingEnd="16dp" android:paddingTop="10dp" android:paddingBottom="10dp"').replace('android:textSize="21sp"','android:textSize="24sp"').replace('android:layout_height="64dp" android:orientation="horizontal" android:background="@color/nav_bg"','android:layout_height="76dp" android:orientation="horizontal" android:background="@color/nav_bg"')
for ident,bg in [('btnBist','@drawable/bg_bist'),('btnViop','@drawable/bg_viop'),('btnOpportunity','@drawable/bg_opportunity')]:
    marker=f'<Button android:id="@+id/{ident}"'
    if marker in s:
        p=s.index(marker); e=s.index('/>',p); frag=s[p:e].replace('android:background="@drawable/bg_surface"',f'android:background="{bg}"'); s=s[:p]+frag+s[e:]
layout.write_text(s,encoding='utf-8')
item=RES/'layout/item_opportunity.xml'; item.write_text('''<?xml version="1.0" encoding="utf-8"?><com.google.android.material.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginStart="4dp" android:layout_marginEnd="4dp" android:layout_marginBottom="8dp" app:cardBackgroundColor="#092033" app:cardCornerRadius="18dp" app:strokeColor="#174662" app:strokeWidth="1dp"><LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content" android:orientation="vertical" android:padding="14dp"><LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content" android:gravity="center_vertical"><LinearLayout android:layout_width="0dp" android:layout_height="wrap_content" android:layout_weight="1" android:orientation="vertical"><TextView android:id="@+id/symbolText" android:layout_width="match_parent" android:layout_height="wrap_content" android:textSize="20sp" android:textStyle="bold" android:textColor="#F4F7FB"/><TextView android:id="@+id/companyNameText" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="2dp" android:textSize="12sp" android:textColor="#A7B5C8" android:maxLines="2" android:ellipsize="end"/></LinearLayout><TextView android:id="@+id/scoreText" android:layout_width="60dp" android:layout_height="44dp" android:gravity="center" android:textSize="18sp" android:textStyle="bold" android:textColor="#FFFFFF" android:background="@drawable/bg_opportunity"/></LinearLayout><TextView android:id="@+id/signalText" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginTop="8dp" android:textStyle="bold" android:textSize="12sp"/><TextView android:id="@+id/priceText" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp" android:textColor="#F4F7FB" android:textSize="14sp"/><TextView android:id="@+id/buyText" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp" android:textColor="#A7B5C8" android:textSize="11sp"/><TextView android:id="@+id/targetText" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="4dp" android:textColor="#A7B5C8" android:textSize="11sp"/><TextView android:id="@+id/stopText" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="4dp" android:textColor="#FF8A1F" android:textSize="11sp"/><TextView android:id="@+id/bedelsizText" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="4dp" android:textColor="#10D977" android:textSize="11sp"/></LinearLayout></com.google.android.material.card.MaterialCardView>\n''',encoding='utf-8')
main=SRC/'MainActivityV4.kt'
if main.exists():
 s=main.read_text(encoding='utf-8').replace('setTextColor(Color.parseColor("#17212B"))','setTextColor(Color.parseColor("#F4F7FB"))').replace('title.text="BORSA TAKİP V4"; subtitle.text="BIST • VİOP • FIRSAT"','title.text="BORSA TAKİP V4.0.4 PRO"; subtitle.text="Borsa fırsatlarını bir adım önce keşfet"').replace('title.text="Takip Listem"; subtitle.text="Canlı fiyat • değişim • yön"','title.text="Takip Listem"; subtitle.text="BIST / VİOP • veri durumu"').replace('title.text="API AYARLARI";subtitle.text="Gerçek piyasa verisi bağlantısı";','title.text="AYARLAR";subtitle.text="Uygulama tercihleri";')
 s=s.replace('val p=getSharedPreferences("market_api_settings",0);findViewById<EditText>(R.id.apiBaseUrlInput)','val p=getSharedPreferences("market_api_settings",0);findViewById<android.widget.Switch>(R.id.demoSwitch).isChecked=p.getBoolean("demo_enabled",false);findViewById<android.widget.Switch>(R.id.notificationSwitch).isChecked=p.getBoolean("notifications_enabled",false);findViewById<android.widget.Switch>(R.id.autoScanSwitch).isChecked=p.getBoolean("auto_scan",false);findViewById<EditText>(R.id.apiBaseUrlInput)')
 s=s.replace('p.edit().putString("base_url",findViewById<EditText>(R.id.apiBaseUrlInput).text.toString().trim()).putString("api_key",findViewById<EditText>(R.id.apiKeyInput).text.toString().trim()).putString("api_secret",findViewById<EditText>(R.id.apiSecretInput).text.toString().trim()).apply();','p.edit().putString("base_url",findViewById<EditText>(R.id.apiBaseUrlInput).text.toString().trim()).putString("api_key",findViewById<EditText>(R.id.apiKeyInput).text.toString().trim()).putString("api_secret",findViewById<EditText>(R.id.apiSecretInput).text.toString().trim()).putBoolean("demo_enabled",findViewById<android.widget.Switch>(R.id.demoSwitch).isChecked).putBoolean("notifications_enabled",findViewById<android.widget.Switch>(R.id.notificationSwitch).isChecked).putBoolean("auto_scan",findViewById<android.widget.Switch>(R.id.autoScanSwitch).isChecked).apply();')
 main.write_text(s,encoding='utf-8')
print('V4.0.4 reference UI applied')
