from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "app/src/main/java/tr/borsatakip/v3"

# V4 kimliği: paket adı geriye dönük uyumluluk için korunur; kullanıcıya görünen
# uygulama ve sınıf kimlikleri V4 olarak temizlenir.
manifest = ROOT / "app/src/main/AndroidManifest.xml"
if manifest.exists():
    s = manifest.read_text(encoding="utf-8")
    s = s.replace('android:label="Borsa Takip V3"', 'android:label="Borsa Takip V4"')
    manifest.write_text(s, encoding="utf-8")

# Uygulamanın görünen V3/V3.2.2 kalıntılarını temizle.
for p in SRC.rglob("*.kt"):
    s = p.read_text(encoding="utf-8")
    s = s.replace("BorsaTakipV3/3.2.6", "BorsaTakipV4/4.0.2")
    s = s.replace("BORSA TAKİP V3.2.2", "BORSA TAKİP V4")
    s = s.replace("BORSA TAKİP V3", "BORSA TAKİP V4")
    s = s.replace("Borsa Takip V3.2.2", "Borsa Takip V4")
    s = s.replace("Borsa Takip V3", "Borsa Takip V4")
    p.write_text(s, encoding="utf-8")

# Launcher activity is renamed to V4 without changing applicationId/namespace,
# so an existing installation remains upgrade-compatible.
old = SRC / "MainActivityV2.kt"
new = SRC / "MainActivityV4.kt"
if old.exists():
    text = old.read_text(encoding="utf-8").replace("class MainActivityV2", "class MainActivityV4")
    new.write_text(text, encoding="utf-8")
    old.unlink()
    s = manifest.read_text(encoding="utf-8").replace(".MainActivityV2", ".MainActivityV4")
    manifest.write_text(s, encoding="utf-8")

# Avoid the old duplicate coroutine imports if an earlier patch left them behind.
main = SRC / "MainActivity.kt"
if main.exists():
    s = main.read_text(encoding="utf-8")
    lines = s.splitlines()
    seen = set(); out=[]
    for line in lines:
        if line.startswith("import kotlinx.coroutines.Dispatchers") or line.startswith("import kotlinx.coroutines.withContext"):
            if line in seen: continue
            seen.add(line)
        out.append(line)
    main.write_text("\n".join(out)+"\n", encoding="utf-8")

# Scoring already contains mandatory gates. Make the production contract explicit:
# demo data is never generated by the application; providers must set isDemo=false.
scoring = SRC / "scoring/ScoringEngine.kt"
if scoring.exists():
    s = scoring.read_text(encoding="utf-8")
    s = s.replace("/** V3.2.7 FIRSAT KONTROLÜ - seçici teknik fırsat motoru. */", "/** V4 FIRSAT KONTROLÜ - yalnızca gerçek veri ve zorunlu kapılardan geçen sonuçlar. */")
    scoring.write_text(s, encoding="utf-8")

print("V4.0.2 completion patch applied")
